### ISSUE TITLE
Sort languages in the same way as Wikipedia

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#328] opened 2017-09-16 01:59 UTC
Please sort languages in the same way as Wikipedia.

![screenshot from 2017-09-16 03-58-33](https://user-images.githubusercontent.com/1583873/30508284-790b4ef2-9a93-11e7-8350-96f2685e9849.png)

**Comment by tstreamDOTh** [comment] 2017-09-16 11:07
I would like to work on this issue. 👍

**Comment by DravitLochan** [comment] 2017-09-16 14:51
@tstreamDOTh  Ok. Please make a relevant PR.

**Comment by jajodiaraghav** [comment] 2017-09-23 11:05
Hi, I think the issue is fixed. Can we close this?

**Comment by tstreamDOTh** [comment] 2017-10-25 18:09
@mariobehling This can be closed?

**Closed** 2018-06-14 15:09 UTC
Labels: enhancement
