### ISSUE TITLE
5 Star skill rating is not working

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_skill_cms#531] opened 2018-05-29 16:36 UTC
**Actual Behaviour**

The 5 star skill rating system is not working. Errors are produced.

**Expected Behaviour**

The skill should be rated properly.

**Steps to reproduce it**

Try rating any skill on the SUSI Skill CMS.

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment] 2018-05-30 12:09
@AnupKumarPanwar This issue is an duplicate of #509. I was waiting for the backend APIs to work as expected before

**Comment by AnupKumarPanwar** [comment] 2018-05-30 14:31
@akshatnitd Ok I've sent a PR for these issues. https://github.com/fossasia/susi_skill_cms/pull/534. Kindly review.

**Comment by anshumanv** [comment] 2018-06-11 02:55
Please close.

**Comment by akshatnitd** [comment] 2018-06-14 18:51
Closing, since already fixed.

**Closed by akshatnitd** 2018-06-14 18:51 UTC
Labels: Analytics, bug
